export const categoryItem = [
  { category_title: "Todos", image: "/propiedades/departamento-losperales-alquiler.png"},
  { category_title: "Venta", image: "/propiedades/departamento-centro-venta.png"},
  { category_title: "Alquiler", image: "/propiedades/local-centro-alquila.png"},
];

export const productsData = [
    {
        id: 1,
        images: [
          '/propiedades/departamento-losperales-alquiler.png', 
          '/propiedades/departamento-losperales-alquila.mp4', 
        ],
        name: 'DEPARTAMENTO en Barrio Los Perales',
        price: "480000",
        category: 'Alquiler',
        description: 'Cocina , comedor, dormitorio,  antebaño baño , balcón y cochera. Para mas información comunicarse al 388-4881245 de 9 a 13 y de 16 a 18 hs. Martillera Sonia Flores MP 177',
        detalles: {
            tipo: 'departamento',
            barrio: 'Los Perales',
            cocheras: 1,
            ambientes:2,
            calle: '',
            numero: '',
            dormitorios: 1,
            banos:2,
            mostrarDireccionExacta: false,
            superficie_m2: "a consultar",
            frente_m: "a consultar",
            fondo_m: "a consultar",
            servicios: ['A consultar'],
            adicionales: ['Cochera'],
            mapaQuery: 'Barrio los Perales, San Salvador de Jujuy',
            lat: -24.16926436167806, 
            lon: -65.32529026568182,
        }
    },
    {
        id: 2,
        images: [
          '/propiedades/local-centro-alquila.png', 
          '/propiedades/local-centro-alquila.mp4', 
        ],
        name: 'Local a pasos de la peatonal',
        price: "A consultar",
        category: 'Alquiler',
        description: 'A metros de la peatonal Belgrano calle Necochea',
        detalles: {
            tipo: 'Local',
            barrio: 'Centro',
            calle: 'Necochea',
            numero: '',
            mostrarDireccionExacta: false,
            superficie_m2: 30,
            frente_m: "a consultar",
            fondo_m: "a consultar",
            ambientes: 1,
            banos: 1,
            servicios: ['Agua Potable', 'Cloaca', 'Electricidad'],
            adicionales: [],
            mapaQuery: 'Barrio Centro, San Salvador de Jujuy',
            lat: -24.185278,
            lon: -65.304163,
        }
    },
    {
        id: 3,
        images: [
          '/propiedades/casa-bajolavina-venta.png', 
          '/propiedades/casa-bajolavina-venta-i1.png', 
          '/propiedades/casa-bajolavina-venta-i2.png',
          '/propiedades/casa-bajolavina-venta-i3.png',
          '/propiedades/casa-bajolavina-venta-i4.png',
          '/propiedades/casa-bajolavina-venta-i5.png',
          '/propiedades/casa-bajolavina-venta-i6.png',
          '/propiedades/casa-bajolavina-venta-i7.png',
          '/propiedades/casa-bajolavina-venta-i8.png',
          '/propiedades/casa-bajolavina-venta-i9.png',
          '/propiedades/casa-bajolavina-venta-i10.png',
          '/propiedades/casa-bajolavina-venta-i11.png',
          '/propiedades/casa-bajolavina-venta-i12.png',
          '/propiedades/casa-bajolavina-venta.mp4',
        ],
        name: 'Casa en Bajo la Viña',
        price: 600000,
        category: 'Alquiler',
        description: 'Casa con dos dormitorios, Living comedor, galeria, entrada para vehiculos. Incluye cocina, comedor, baño, galeria, entrada para Vehiculos. Para mas información comunicarse al 388-4881245 de 9 a 13 y de 16 a 18 hs. Martillera Sonia Flores MP 177',
        detalles: {
            tipo: 'Casa',
            barrio: 'Bajo la Viña',
            calle: 'A consultar',
            numero: 'A consultar',
            mostrarDireccionExacta: false,
            superficie_m2: "A consultar",
            ambientes: "A consultar",
            dormitorios: 2,
            banos: 1,
            servicios: ['Agua Potable', 'Cloaca', 'Gas Embasado', 'Electricidad'],
            adicionales: [],
            mapaQuery: 'Patricias Argentinas 400, Centro, San Salvador de Jujuy',
            lat: -24.180282869247712, 
            lon: -65.28602468805403
        }
    },
    {
        id: 4,
        images: [
        '/propiedades/oficina-centro-venta.png',
        '/propiedades/oficina-centro-venta-i1.png',
        '/propiedades/oficina-centro-venta-i3.png',
        '/propiedades/oficina-centro-venta-i4.png',
        '/propiedades/oficina-centro-venta-i5.png',
        '/propiedades/oficina-centro-venta-i6.png',
        '/propiedades/oficina-centro-venta-i7.png',
        '/propiedades/oficina-centro-venta-i8.png',
        '/propiedades/oficina-centro-venta-i9.png',
        ],
        name: 'Oficina céntrica con vista a la calle',
        price: 'A consultar',
        category: 'Venta',
        description: 'Excelente oficina ubicada en primer piso, con vista a la calle y emplazada en una zona céntrica. Ideal para estudios profesionales, consultorios u oficinas comerciales. Una excelente oportunidad de inversión, con opciones de entrega y financiación. Para mas información comunicarse al 388-4881245 de 9 a 13 y de 16 a 18 hs. Martillera Sonia Flores MP 177 ',
        detalles: {
            tipo: 'Oficina',
            barrio: 'Centro',
            calle: 'Guemes y Necochea',
            numero: '',
            mostrarDireccionExacta: false,
            superficie_m2: "", 
            ambientes: 1,
            dormitorios: 0,
            banos: 1,
            servicios: ['Agua Potable', 'Cloaca', 'Electricidad'],
            adicionales: [
            ],
            mapaQuery: 'Centro, San Salvador de Jujuy',
            lat: -24.182943, 
            lon: -65.304468,
    }
},
    {
        id: 5,
        images: [
          '/propiedades/deposito-altocomedero-alquiler.png', 
          '/propiedades/deposito-altocomedero-alquiler-i1.png', 
          '/propiedades/deposito-altocomedero-alquiler-i2.png',
          '/propiedades/deposito-altocomedero-alquiler-i3.png',
          '/propiedades/deposito-altocomedero-alquiler-i4.png',
          '/propiedades/deposito-altocomedero-alquiler-i5.png',
          '/propiedades/deposito-altocomedero-alquiler-i6.png',
          '/propiedades/deposito-altocomedero-alquiler-i7.png',
          '/propiedades/deposito-altocomedero-alquiler-i8.png',
        ],
        name: 'Depósito/Galpón de 300 m² frente a Ruta N° 9 en Alto Comedero',
        price: 2000000,
        category: 'Alquiler',
        description: 'Depósito a estrenar ubicado frente a Ruta Nacional N° 9, en Barrio Alto Comedero. Cuenta con salón, baño, kitchenette y patio. Superficie de 300 m², con opción de alquilar 600 m². Para mas información comunicarse al 388-4881245 de 9 a 13 y de 16 a 18 hs. Martillera Sonia Flores MP 177',
        detalles: {
            tipo: 'Depósito',
            barrio: 'Alto Comedero',
            calle: 'Ruta Nacional N° 9',
            numero: '',
            mostrarDireccionExacta: false,
            superficie_m2: 300,
            frente_m: 0,
            fondo_m: 0,
            ambientes: 1,
            banos: 1,
            expensas: 0,
            servicios: ['Agua Potable', 'Cloaca', 'Electricidad', 'Pavimento'],
            adicionales: ['A estrenar', 'Kitchenette', 'Patio', 'Frente a Ruta Nacional N° 9', 'Opción 600 m²'],
            mapaQuery: 'Ruta Nacional 9, Alto Comedero, San Salvador de Jujuy',
            lat: -24.218112,
            lon: -65.272239,
        }
    },
    {
        id: 6,
        images: [
          '/propiedades/departamento-centro-venta.png', 
          '/propiedades/departamento-centro-venta-i1.png', 
          '/propiedades/departamento-centro-venta-i2.png',
          '/propiedades/departamento-centro-venta-i3.png',
          '/propiedades/departamento-centro-venta-i4.png',
          '/propiedades/departamento-centro-venta-i5.png',
          '/propiedades/departamento-centro-venta-i6.png',
          '/propiedades/departamento-centro-venta-i7.png',
          '/propiedades/departamento-centro-venta-i8.png',
          '/propiedades/departamento-centro-venta-i9.png',
          '/propiedades/departamento-centro-venta-i10.png',
          '/propiedades/departamento-centro-venta-i11.png',
          '/propiedades/departamento-centro-venta-i12.png',
          '/propiedades/departamento-centro-venta-i13.png',
          '/propiedades/departamento-centro-venta-i14.png',
        ],
        name: 'Departamento de 1 dormitorio cerca del Parque San Martín',
        price: 'A consulta',
        category: 'Venta',
        description: 'Departamento con excelente ubicación, a pocos metros del Parque San Martín. Cuenta con comedor, cocina, un dormitorio y baño. Ideal para vivienda o inversión. Para mas información comunicarse al 388-4881245 de 9 a 13 y de 16 a 18 hs. Martillera Sonia Flores MP 177',
        detalles: {
            tipo: 'Departamento',
            barrio: 'Centro',
            calle: '',
            numero: '',
            mostrarDireccionExacta: false,
            superficie_m2: 0,
            ambientes: 3,
            dormitorios: 1,
            banos: 1,
            expensas: 0,
            servicios: ['Agua Potable', 'Cloaca', 'Electricidad', 'Pavimento',"gas"],
            adicionales: ['Excelente ubicación', 'Cerca del Parque San Martín'],
            mapaQuery: 'Parque San Martín, San Salvador de Jujuy',
            lat: -24.189119,
            lon: -65.297721,
        }
    },
    {
        id: 7,
        images: [
          '/propiedades/departamentos-pasaje-alquiler.png', 
          '/propiedades/departamento-pasaje-alquila.mp4', 
        ],
        name: 'Departamentos de 1 dormitorio en Pasaje El Tala',
        price: 400000,
        category: 'Alquiler',
        description: 'Departamento amplio y luminoso, ideal para una persona o pareja. Cuenta con un dormitorio, cocina comedor, baño y balcón. Excelente ubicación en Pasaje El Tala. Para mas información comunicarse al 388-4881245 de 9 a 13 y de 16 a 18 hs. Martillera Sonia Flores MP 177',
        detalles: {
            tipo: 'Departamento',
            barrio: 'Cuyaya',
            calle: 'Pasaje El Tala',
            numero: '',
            mostrarDireccionExacta: false,
            superficie_m2: 0,
            ambientes: 2,
            dormitorios: 1,
            banos: 1,
            expensas: 0,
            servicios: ['Agua Potable', 'Cloaca', 'Electricidad', 'Pavimento',"gas"],
            adicionales: ['Balcón', 'Amplio y luminoso', 'Ideal para una persona o pareja', 'Excelente ubicación'],
            mapaQuery: 'Pasaje El Tala, San Salvador de Jujuy',
            lat: -24.186500,
            lon: -65.297800,
        }
    },
    {
        id: 8,
        images: [
          '/propiedades/departamento-brown-alquiler.png', 
          '/propiedades/departamento-brown-alquila.mp4', 
        ],
        name: 'Departamento de 2 dormitorios sobre Av. Almirante Brown',
        price: 470000,
        category: 'Alquiler',
        description: 'Departamento ubicado sobre Av. Almirante Brown. Cuenta con cocina, 2 dormitorios (uno con aire acondicionado), baño y dos balcones pequeños. Expensas aproximadas de $30.000. Excelente opción para quienes buscan comodidad y buena ubicación. Para mas información comunicarse al 388-4881245 de 9 a 13 y de 16 a 18 hs. Martillera Sonia Flores MP 177',
        detalles: {
            tipo: 'Departamento',
            barrio: 'barrio Almirante Brown',
            calle: 'Av. Almirante Brown',
            numero: '',
            mostrarDireccionExacta: false,
            superficie_m2: 0,
            ambientes: 3,
            dormitorios: 2,
            banos: 1,
            expensas: 30000,
            servicios: ['Agua Potable', 'Cloaca', 'Electricidad', 'Pavimento',"ga"],
            adicionales: ['Aire acondicionado en un dormitorio', '2 balcones'],
            mapaQuery: 'Avenida Almirante Brown, San Salvador de Jujuy',
            lat: -24.202653,
            lon: -65.284040,
        }
    },
    {
        id: 9,
        images: [
          '/propiedades/departamento-losperales-alquila-n2.png', 
          '/propiedades/departamento-losperales-alquila-n2.mp4', 
        ],
        name: 'Departamento de 2 dormitorios con excelente vista',
        price: 700000,
        category: 'Alquiler',
        description: 'Departamento con living comedor, cocina, dos dormitorios, baño, lavadero y balcón. Se destaca por su excelente vista e iluminación natural. Para mas información comunicarse al 388-4881245 de 9 a 13 y de 16 a 18 hs. Martillera Sonia Flores MP 177',
        detalles: {
            tipo: 'Departamento',
            barrio: 'Los Perales',
            calle: '',
            numero: '',
            mostrarDireccionExacta: false,
            superficie_m2: 0,
            ambientes: 4,
            dormitorios: 2,
            banos: 1,
            expensas: 0,
            servicios: ['Agua Potable', 'Cloaca', 'Electricidad', 'Pavimento',"gas"],
            adicionales: ['Lavadero', 'Balcón', 'Excelente vista', 'Iluminación natural'],
            mapaQuery: 'San Salvador de Jujuy',
            lat: -24.185786,
            lon: -65.299476,
        }
    },
    {
        id: 10,
        images: [
          '/propiedades/departamento-centro-alquila.png', 
          '/propiedades/departamento-centro-alquila.mp4', 
        ],
        name: 'Departamento de 6 ambientes en el Microcentro',
        price: 1500000,
        category: 'Alquiler',
        description: 'Amplio departamento ubicado en pleno microcentro de San Salvador de Jujuy. Cuenta con 6 ambientes, baño, cocina, patio y dos balcones de uso exclusivo. Se destaca por su excelente iluminación natural. Ideal para vivienda familiar o para uso comercial. Para mas información comunicarse al 388-4881245 de 9 a 13 y de 16 a 18 hs. Martillera Sonia Flores MP 177',
        detalles: {
            tipo: 'Departamento',
            barrio: 'Microcentro',
            calle: 'Necochea y Belgrano',
            numero: '',
            mostrarDireccionExacta: false,
            superficie_m2: 0,
            ambientes: 6,
            dormitorios: 0,
            banos: 1,
            expensas: 0,
            servicios: ['Agua Potable', 'Cloaca', 'Electricidad', 'Pavimento',"gas"],
            adicionales: [
                '2 balcones de uso exclusivo',
                'Patio',
                'Excelente luz natural',
                'Apto vivienda familiar',
                'Apto local comercial'
            ],
            mapaQuery: 'Microcentro, San Salvador de Jujuy',
            lat: -24.185786,
            lon: -65.299476,
        }
    },
    {
        id: 11,
        images: [
          '/propiedades/departamento-centro-alquila-n2.png', 
          '/propiedades/departamento-centro-alquila-n2.mp4', 
        ],
        name: 'Departamento de 3 dormitorios en Barrio Centro',
        price: 800000,
        category: 'Alquiler',
        description: 'Amplio departamento ubicado en Barrio Centro. Cuenta con living comedor, cocina, 3 dormitorios con placares, lavadero, habitación de servicio, baño de servicio y un amplio balcón. Excelente vista e iluminación natural. Para mas información comunicarse al 388-4881245 de 9 a 13 y de 16 a 18 hs. Martillera Sonia Flores MP 177',
        detalles: {
            tipo: 'Departamento',
            barrio: 'Centro',
            calle: '',
            numero: '',
            mostrarDireccionExacta: false,
            superficie_m2: 0,
            ambientes: 5,
            dormitorios: 3,
            banos: 2,
            expensas: 0,
            servicios: ['Agua Potable', 'Cloaca', 'Electricidad', 'Pavimento',"gas"],
            adicionales: [
                'Placares en los dormitorios',
                'Lavadero',
                'Habitación de servicio',
                'Baño de servicio',
                'Amplio balcón',
                'Excelente vista',
                'Iluminación natural'
            ],
            mapaQuery: 'Centro, San Salvador de Jujuy',
            lat: -24.187271429334597,
            lon: -65.30912978971212,
        }
    },
    {
        id: 12,
        images: [
          '/propiedades/casa-chijra-venta.png', 
          '/propiedades/casa-chijra-venta.mp4', 
          '/propiedades/tr3.jpg'
        ],
        name: 'Casa con departamento independiente a 30 m de Av. Mosconi',
        price: 'A consulta',
        category: 'Venta',
        description: 'Excelente propiedad desarrollada en dos plantas. En planta baja cuenta con living comedor, cocina comedor, dos dormitorios, habitación de usos múltiples, asador y cochera. En planta alta dispone de un departamento con entrada independiente, living comedor, amplia cocina con comedor diario, un dormitorio y baño. Todos los servicios y excelente ubicación, a solo 30 metros de Av. Mosconi. Para mas información comunicarse al 388-4881245 de 9 a 13 y de 16 a 18 hs. Martillera Sonia Flores MP 177',
        detalles: {
            tipo: 'Casa',
            barrio: 'Chijra',
            calle: 'Av. Mosconi',
            numero: '',
            mostrarDireccionExacta: false,
            superficie_m2: 0,
            ambientes: 8,
            dormitorios: 3,
            banos: 2,
            expensas: 0,
            servicios: ['Agua Potable', 'Cloaca', 'Gas Natural', 'Electricidad', 'Pavimento'],
            adicionales: [
                'Departamento con entrada independiente',
                'Habitación de usos múltiples',
                'Asador',
                'Cochera',
                'Comedor diario',
                'Excelente ubicación',
                'A 30 m de Av. Mosconi'
            ],
            mapaQuery: 'Avenida Mosconi, San Salvador de Jujuy',
            lat: -24.174281946644435,
            lon: -65.30463208760564,
        }
    },
    {
        id: 13,
        images: [
          '/propiedades/departamento-sanpedrito-alquila.png', 
          '/propiedades/departamento-sanpedrito-alquila.mp4', 
        ],
        name: 'Departamento de 1 dormitorio en Planta Baja en San Pedrito',
        price: 400000,
        category: 'Alquiler',
        description: 'Departamento en planta baja ubicado en Barrio San Pedrito. Cuenta con cocina comedor, baño y dormitorio. Excelente opción de alquiler en una zona de fácil acceso. Para mas información comunicarse al 388-4881245 de 9 a 13 y de 16 a 18 hs. Martillera Sonia Flores MP 177',
        detalles: {
            tipo: 'Departamento',
            barrio: 'San Pedrito',
            calle: 'Gobernador Tello',
            numero: '',
            mostrarDireccionExacta: false,
            superficie_m2: 0,
            ambientes: 2,
            dormitorios: 1,
            banos: 1,
            expensas: 0,
            servicios: ['Agua Potable', 'Cloaca', 'Gas Natural', 'Electricidad', 'Pavimento'],
            adicionales: ['Planta Baja'],
            mapaQuery: 'Gobernador Tello, Barrio San Pedrito, San Salvador de Jujuy',
            lat: -24.203559103532267,
            lon: -65.27390369740094,
        }
    },
    {
        id: 14,
        images: [
          '/propiedades/hectareas-sanantonio-venta.png', 
          '/propiedades/hectareas-sanantonio-venta.mp4', 
        ],
        name: 'Terreno de 20 hectáreas en San Antonio',
        price: 'A consultar',
        category: 'Venta',
        description: 'Campo de 20 hectáreas ubicado en San Antonio, sobre El Camino Real. Superficie totalmente plana, ideal para diversos emprendimientos. Zona con gran valor cultural e histórico por ser punto de partida de la Marcha Patriótica por el Camino Real. Para mas información comunicarse al 388-4881245 de 9 a 13 y de 16 a 18 hs. Martillera Sonia Flores MP 177',
        detalles: {
            tipo: 'Terreno',
            barrio: 'San Antonio',
            calle: 'Camino Real',
            numero: '',
            mostrarDireccionExacta: false,
            superficie_m2: 200000,
            servicios: [],
            adicionales: [
                'Superficie totalmente plana',
                'Ideal para emprendimientos',
                'Ubicación con valor histórico y cultural'
            ],
            mapaQuery: 'Camino Real, San Antonio, Jujuy',
            lat: -24.365787548293422, 
            lon: -65.33530500933232,
        }
    },
    {
        id: 15,
        images: [
          '/propiedades/oficina-centro-alquila-n2.png', 
          '/propiedades/oficina-centro-alquila.mp4', 
        ],
        name: 'Oficinas en 1° piso en pleno Centro',
        price: 500000,
        category: 'Alquiler',
        description: 'Dos oficinas en alquiler ubicadas en pleno centro. Cuenta con sala de espera y baño, ideales para profesionales, estudios u oficinas administrativas. Para mas información comunicarse al 388-4881245 de 9 a 13 y de 16 a 18 hs. Martillera Sonia Flores MP 177',
        detalles: {
            tipo: 'Oficina',
            barrio: 'Centro',
            calle: '',
            numero: '',
            mostrarDireccionExacta: false,
            superficie_m2: 0,
            ambientes: 3,
            dormitorios: 0,
            banos: 1,
            expensas: 0,
            servicios: ['Agua Potable', 'Cloaca', 'Electricidad', 'Pavimento'],
            adicionales: ['1° piso', 'Sala de espera', 'Dos oficinas', 'Pleno centro'],
            mapaQuery: 'Centro, San Salvador de Jujuy',
            lat: -24.182925943398676, 
            lon: -65.30921562039984,
        }
    },
]